# Generated by Django 3.2.6 on 2021-08-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2_app', '0004_alter_doctor_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='img',
            field=models.ImageField(blank=True, upload_to='department'),
        ),
    ]
