# Generated by Django 3.2.6 on 2021-08-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2_app', '0005_alter_doctor_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='img',
            field=models.ImageField(upload_to='department'),
        ),
    ]
